Makefile(s) polishing
angelcam/turris-packages pull request #6
Opened 2022-06-07 10:51 UTC by BKPepe

This is based on PR https://github.com/angelcam/turris-packages/pull/5

A rather few formal things, which are not tested, yet. Thus PR is marked as draft until the test will be perfomed if it is alright.

2022-06-08 08:00 UTC, operutka reviewed
Since your changes are mostly code style related, I have to ask - is there any official OpenWrt code style guideline or is it just your feeling here? :)

I'm asking because, in my experience, when people start enforcing code style that's based only on their feeling, sooner or later there will be someone who has a different feeling about it. That would make changes like that quite pointless.

2022-06-08 08:43 UTC, BKPepe commented
Regarding the code style) 

Yes, you are right that my changes are related to it, but with the things how it goes, I think my colleague is in touch with you, and there were some improvements that you are not using the host system directory anymore to install rust, but host folder in a build system. Even though there should be more changes, I think we can not do anything better right now as first Rust needs to be added to OpenWrt, in your case, and if it is not there, we can just make it work somehow for a few routers even in a hacky way and see if anyone uses it. Also, I did not look at it further as there will be more changes because currently, Turris 1.x routers are not supported, and it fails the entire build for it. I did not submit those changes yet as I don't want to commit changes any other except formal things, which I did not test.

Good question about official guidelines or not, and yes, I can confirm the same behavior from my experience. I would say that there are no official guidelines and you will need to force users to let them know about it by using CI, but many packages in the same-named repository were improved over the past, and since that, they have been trying to stick with it.

For reference: https://github.com/openwrt/packages/issues/9682

2022-06-08 08:44 UTC, BKPepe commented on rust-lang/Makefile
> +PKG_VERSION:=1.24.3
Hmm, interesting. Yes, you were saying those different in some PR/issue, but I find this still confusing how it is done. I will rework it to be clear to anyone, no problem at all.

2022-06-08 12:47 UTC, operutka commented
> Also, I did not look at it further as there will be more changes because currently, Turris 1.x routers are not supported, and it fails the entire build for it.

I can fix the build but I don't have the device to test it.

2022-08-09 18:59 UTC, BKPepe commented on rust-lang/Makefile
> +PKG_VERSION:=1.24.3
Reworked.

2022-08-09 19:06 UTC, BKPepe commented
> Do you have any comments on the package version (see my comment above)?

Yes, I had, but I did the changes for you, so it now should be clear how it should be done for OpenWrt build system because you can not use PKG_VERSION and PKG_SOURCE_VERSION at the same time, which results that both versions being different. You were downloading and checking out the rust-up repository for version 1.24.3 and not 1.6.0.

I can extend the commit messages, if you want.

> I can fix the build but I don't have the device to test it.

You don't need to have the device to test whether it compiles. At least your feed does not crash the entire build anymore.  We should move this discussion to https://github.com/angelcam/turris-packages/issues/7

___

My pull request is now compile tested for Turris Omnia and Turris MOX.

2022-08-15 09:28 UTC, operutka requested changes
Thank you for the update. However, I'm still not happy with the `PKG_VERSION`. As I mentioned before, the package does not install Rusup, it installs Rust. Rustup is just a simple tool, for installing/updating Rust and the related ecosystem. Therefore, `PKG_VERSION` should be a version of Rust here (see the proposed changes).

If we used the Rustup version here, it would be like creating a Python package but instead of putting a Python version into the `PKG_VERSION`, we'd be using a pip version.

Alternatively, we could split this package into two. One would be responsible for installing Rustup and the other would be responsible for installing Rust (using Rustup).

2022-08-15 09:28 UTC, operutka commented on rust-lang/Makefile
> +PKG_VERSION:=1.25.1
```suggestion
PKG_VERSION:=1.60.0
```

2022-08-15 09:28 UTC, operutka commented on rust-lang/Makefile
> +PKG_SOURCE:=rustup-$(PKG_VERSION).tar.gz
```suggestion
PKG_SOURCE:=rustup-1.25.1.tar.gz
```

2022-08-15 09:28 UTC, operutka commented on rust-lang/Makefile
> +PKG_SOURCE_URL:=https://codeload.github.com/rust-lang/rustup/tar.gz/$(PKG_VERSION)?
```suggestion
PKG_SOURCE_URL:=https://codeload.github.com/rust-lang/rustup/tar.gz/1.25.1?
```

2022-08-15 09:28 UTC, operutka commented on rust-lang/Makefile
> +		--default-toolchain 1.60.0 \
```suggestion
		--default-toolchain $(PKG_VERSION) \
```

2022-08-15 09:31 UTC, BKPepe commented on rust-lang/Makefile
> +PKG_VERSION:=1.25.1
No, this is not correct as I pointed out. You are trying to persued building system and its variables to do something different than it is used to. If you take a look at [OpenWrt documentation](https://openwrt.org/docs/guide-developer/packages), you see that the version there is used to download it and that's what it should be in PKG_SOURCE and PKG_SOURCE_URL. There should not be a hard-coded version, but PKG_VERSION.

2022-08-15 09:43 UTC, operutka commented on rust-lang/Makefile
> +PKG_VERSION:=1.25.1
I understand but the current solution isn't correct either (semantically). Would you be comfortable with splitting this package into two as I proposed (one package for Rustup and one for Rust)?

2022-08-15 09:45 UTC, BKPepe commented on rust-lang/Makefile
> +PKG_VERSION:=1.25.1
Because we are not able to agree on my solution and I don't like yours! :laughing: Then, yeah, splitting the package into two sounds reasonable.

2022-08-15 09:55 UTC, operutka commented on rust-lang/Makefile
> +PKG_VERSION:=1.25.1
Perfect! :smile: 

Then I propose the following:

1. I will merge this PR as it is.
2. I will merge also #5.
3. I will create a new PR splitting this package into two.

2022-08-15 09:57 UTC, BKPepe commented
Sounds good.

Dne po 15. 8. 2022 11:55 uživatel Ondřej Perutka ***@***.***>
napsal:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In rust-lang/Makefile
> <https://github.com/angelcam/turris-packages/pull/6#discussion_r945580158>
> :
>
> > @@ -1,24 +1,37 @@
>
>  include $(TOPDIR)/rules.mk
>
>
>
> -PKG_NAME := rust-lang
>
> -PKG_LICENSE := Apache-2.0/MIT
>
> -PKG_VERSION := 1.60.0
>
> -PKG_RELEASE := 1
>
> +PKG_NAME:=rust-lang
>
> +PKG_VERSION:=1.25.1
>
>
> Perfect! 😄
>
> Then I propose the following:
>
>    1. I will merge this PR as it is.
>    2. I will merge also #5
>    <https://github.com/angelcam/turris-packages/pull/5>.
>    3. I will create a new PR splitting this package into two.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/angelcam/turris-packages/pull/6#discussion_r945580158>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA7IDVEYH6GD3XQUKOM6HBLVZIHYNANCNFSM5YCPJJ5A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-15 09:59 UTC, operutka approved these changes

2022-08-15 10:00 UTC, merged